### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by RexProg** [oleg-shilo/cs-script.npp#3]
If it is possible please record a video about manual installation
I have a problem in add reference 
When I use //CSS_ref sn.DLL
Output have an exception
Metadata was not found
However in panel added in reference

**Comment by oleg-shilo** [comment]
You nominated two problems: "manual installation" and problem with referencing assemblies. These problem have nothing in common so they need to be handles individually.

- _Installation_ 
    If indeed you have problem with installation (e.g. plugin does not work) then please provide the description.

- _Assembly referencing_
    Ideally I would need you to provide the code sample so I can investigate. But befor you do this please do the test by replacing `//CSS_ref sn.DLL` with `//css_ref <absolute path to sn.DLL>` (note that the directive is all in lowercase). Let me know how it goes.

**Comment by RexProg** [comment]
Excuse me I type this message by phone 
I use want to add reference  [dnlib.zip](https://github.com/oleg-shilo/cs-script.npp/files/1056678/dnlib.zip) 
Please test it 
I cannot add it
[Examples](https://github.com/0xd4d/dnlib/tree/master/Examples)

I say "I have problem in installation" because i see %CSSCRIPT_DIR% in the configuration of plugin but it isn't set in environment variable

**Comment by oleg-shilo** [comment]
The attached file shows how to reference the dll:
[New folder.zip](https://github.com/oleg-shilo/cs-script.npp/files/1056709/New.folder.zip)

As for "%CSSCRIPT_DIR%" it is set system wide when you install CS-Script. However none of the CS-Script.Npp configs relies on "%CSSCRIPT_DIR%" unless user sets it otherwise. Please provide your config file so I can advice you how to fix the problem.

**Comment by dunha** [comment]
Hi
Not sure if I should have started another thread, but I would like to know if a zip file of the installation is available for download
My problem is that I do not have permission to install it through the plugin manager, so I used to update with Csscript updater manually, but now it reports that I am up to date with 1.7.5 and plugin manager reports 1.7.6 available
Thanks for the great work

**Comment by oleg-shilo** [comment]
My mistake. The CS-Script.Npp updater was not bound to the latest plugin release. The problem is corrected now. So you should be able to update it as usual.
I there are any problems you can download the plugin directly from here: www.csscript.net/npp/CSScriptNpp.1.7.6.0.zip

Please note that I am about to start field testing of the plugin portable version (with long awaited x64 support).

Thus there will be another update soon.

**Comment by dunha** [comment]
Thanks. I keep getting failed installs because of the admin permissions required for plugin manager, and for other plugins
I'll look forward to the new version

**Comment by oleg-shilo** [comment]
Then indeed your chance is that direct link I provided.
Though keep in mind that with the the next version you will face the same challenge. You will need to be an admin to use NPP managed (or CS-Script.Npp updater).

**Comment by dunha** [comment]
That's fine, Your updater allows for manual download anyway
Cheers
