### ISSUE TITLE
Internet or Restriced zone error

### ISSUE THREAD

**Issue by sadasd1** [oleg-shilo/cs-script.npp#36]
Hi,

When I try to compile sourceCode for CSScriptNPP, I get the following errors
![image](https://user-images.githubusercontent.com/25536966/54152333-63be6400-4413-11e9-9599-03502fcf6914.png)

Thanks.

**Comment by oleg-shilo** [comment]
This is not a problem with the codebase as such but rather with the project location and your Visual Studio deployment. Is there any chance you are building it from the network?

**Comment by anthonynorthrup314** [comment]
This thread is a bit old, but the real cause of this issue is likely that it was downloaded as a ZIP and has the "mark of the web" on it (as shown in your screenshot). To resolve this issue, you'll simply need to unblock each of the files reporting an error:
https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/

There is also a wonderful SO post detailing how to unblock the files with PowerShell:
https://stackoverflow.com/a/51349305
