### ISSUE TITLE
Where is the main documentation page "cs-script.net"?

### ISSUE THREAD

**Issue by it19862** [oleg-shilo/cs-script.npp#51]
Where is the main documentation page "cs-script.net"?
I have links to the pages
https://www.cs-script.net/cs-script/help-legacy/Adding_Searchdirs.html
https://www.cs-script.net/cs-script/help-legacy/Importing_scripts.html
and other pages.

Where is the main documentation page located `cs-script.net`, where are the links to similar pages of the `site`located?

**Comment by oleg-shilo** [comment]
It is Wiki that you are looking for:
https://github.com/oleg-shilo/cs-script/wiki

Every github project has wiki tab where the documentation is typically located.

Though, since you are reporting it on N++ site I assume you are trying to use CS-Script from N++. 
If it is the case then the legacy documentation is still in large degree accurate: https://www.cs-script.net/cs-script/help-legacy/root/

But... the most accurate documentation is the output of `cscs.exe -?`: https://github.com/oleg-shilo/cs-script/blob/master/help.txt
