### ISSUE TITLE
New Install - "Cannot use alternative compiler" error

### ISSUE THREAD

**Issue by harecu** [oleg-shilo/cs-script.npp#63]
Installed CS-Script via the Plugin Admin and loaded a blank script via the New Script button, built Hello World script and got this error:

System.ApplicationException: Cannot use alternative compiler (C:\ProgramData\CS-Script\CSScriptNpp\1.7.26.0\CSSRoslynProvider.dll). You may want to adjust 'CSSCRIPT_DIR' environment variable or disable alternative compiler by setting 'useAlternativeCompiler' to empty value in the css_config.xml file.
Error Details: ---> System.ApplicationException: Cannot find alternative compiler "C:\ProgramData\CS-Script\CSScriptNpp\1.7.26.0\CSSRoslynProvider.dll"

CS-Script v1.7.27
Notepad++ v8.1.9.3 (64 bit)

**Comment by oleg-shilo** [comment]
Is compiler dll there? The error message says it cannot find it. 

Nevertheless, if you do not want to troubleshoot you can switch to the .NET Core (.NET 6) engine instead of using the default engine that comes with the plugin and relies on .NET Framework.

If you opt for this solution then you will need to install .NET 6 and then activate the plugin integration from the about box (it will install the required dependencies for you.
Have a look at this wiki, it describes the process: https://github.com/oleg-shilo/cs-script.npp/wiki/.NET-Core
  
I would advise you to switch to .NET core since .NET Framework is effectively no longer an active stream of .NET.
I am not making .NET Core a default option as now it is a transition phase for many .NET users but in the near future, I will.

**Comment by harecu** [comment]
Thanks for your reply. The dll is not there, the folders appear to be
empty. I will switch over like you suggested, thanks!

**Comment by oleg-shilo** [comment]
But of course, you can turn the alternative compiler off and start experimenting with the product.
You can do it by setting 'useAlternativeCompiler' to empty value in the css_config.xml file.
