### ISSUE TITLE
Console output displays umlauts/vovel mutations wrong - Can't make any user input in the output window

### ISSUE THREAD

**Issue by ghost** [oleg-shilo/cs-script.npp#68]
Notepad++ 8.1.4 64-bit
CSScriptNpp 1.7.24.0

Hello,

I'm new to programming and notepad++ with CSScript.Npp.

My first problem is that the output window displays umlauts incorrectly.
I read about Console.OutputEncoding = System.Text.Encoding.UTF8; in the FAQ but experimenting with it won't solve the issue, maybe since I don't know what I'm really doing.

Secondary, when I run a script asking for user input, I can't make any.

Can anybody help me with that?

Thanks and kind regards,

Marek

**Comment by oleg-shilo** [comment]
Hi Marek, console output panel is for output. If you are to make an input then you need to run the script on its own. You need to run it as an external script (select the command from the Npp menu.

As for any non-ASCII characters then out of box the extensиon supports it:

![image](https://user-images.githubusercontent.com/16729806/163885140-92d63e77-2b87-4f93-875a-4db220b185ae.png)

However if the app/script for some reason brea=kes console encoding then indeed it is a problem. In such case it is safer to set console to the desired encoding at the start of the script with `Console.OutputEncoding = System.Text.Encoding.UTF8;`.

if it does not help then just send me the piece of output that you are trying to use and I have a look.

BTW, please use the latest release (yesterday): https://github.com/oleg-shilo/cs-script.npp/releases/tag/v2.0.0.0-rc
It is a complete port of the plugin and the extension to .NET6.
Though since it is not published on Npp repo then you need to do it manually: https://github.com/oleg-shilo/cs-script.npp/wiki/Manual-Installation.
