### ISSUE TITLE
target .net framework vs .net core in cs-script 4.4.8.0

### ISSUE THREAD

**Issue by KareemAaron** [oleg-shilo/cs-script.npp#71]
Indeed, the current release of CS-Script targets .NET Core family runtime (.NET 6).

However, I still needed to write, debug, and test code in .net Framework 4.0.

How can I configure cs-script to target .net 4.0?

My system info is provided below.

cs-script.npp 2.0.2.0
cs-script 4.4.8.0
Window 10 Pro 10.0.19044 N/A Build 1904

C:\Program Files\dotnet>dotnet.exe --list-runtimes
Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

C:\Program Files\dotnet>dotnet.exe --list-sdks
5.0.300 [C:\Program Files\dotnet\sdk]

C:\Program Files\dotnet>reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP"
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\CDF
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4.0

**Comment by oleg-shilo** [comment]
It is a difficult one. Since .NET Framework is no longer in the .NET roadmap CS-SCript also has switched to .NET Core family.

You can definitely install CS-Release that targets .NET Framework ([from here](https://github.com/oleg-shilo/cs-script.net-framework/releases/tag/split-point)).

When it comes to Notepad++ you would be able to simply install an older version of the plugin but unfortunately, Notepad++ team has implemented recently some hosting API changes that invalidate some many older plugins including CS-Script. 

Thus you will need to use Visual Studio for debugging. Or...you can use VSCode with CS_Script extension that supports debugging in the same IDE.

**Comment by KareemAaron** [comment]
I use notepad++ (npp) portable. I'm considering downloading an older version of the application just to use cs-script.npp targeting .net 4.0. 

I went back to npp 8.0.0 and  CSScriptNpp.1.7.26.0.x64 but intellisense wasn't working.

Would you happen to recall the combination of npp and cs-script.npp that was the most stable (i.e., all features available including intelligence) when targeting .net 4.0?

**Comment by oleg-shilo** [comment]
This combination seems to work:

![image](https://user-images.githubusercontent.com/16729806/195988135-4162a83c-18eb-4d2f-a2b5-30891d2436f6.png)

![image](https://user-images.githubusercontent.com/16729806/195988158-796cd576-04f4-46c4-b41c-64ebde0913ca.png)

![image](https://user-images.githubusercontent.com/16729806/195988190-bb2ac6e2-3596-471a-a03b-84e3cd121102.png)
